# Numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

### Arreglos

In [3]:
arr = np.array([1,2,3])

print(arr)

[1 2 3]


In [4]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
arr = np.array([1,2,3,4,5,6], ndmin=3)
print(arr.ndim) #Propiedad dimensión
print(arr)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])

3
[[[1 2 3 4 5 6]]]
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
1


In [12]:
arr = np.zeros((2,2))
print(arr)

[[0. 0.]
 [0. 0.]]


In [9]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
arr = np.random.rand(3,3)
print(arr)

[[0.54926355 0.30849339 0.42340303]
 [0.22142018 0.1214385  0.28110756]
 [0.74504948 0.15098718 0.25804592]]


### Operaciones

In [13]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = np.add(arr1,arr2)
print(arr3)

[5 7 9]


In [16]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3=np.subtract(arr2,arr1)
print(arr3)

[3 3 3]


In [17]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3=np.multiply(arr2,arr1)
print(arr3)

[ 4 10 18]


In [18]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3=np.divide(arr1,arr2)
print(arr3)

[0.25 0.4  0.5 ]


### Agregación (Media, mediana, moda, etc...)

In [20]:
arr = [1,5,7]
media = np.mean(arr)
print(media)

4.333333333333333


In [21]:
arr = [1,5,7]
mediana = np.median(arr)
print(mediana)

5.0


In [22]:
arr = [1,5,7]
maximo = np.max(arr)
print(maximo)

7


In [23]:
arr = [1,5,7]
minimo = np.min(arr)
print(minimo)

1


### Indexación

In [24]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])

1


In [25]:
arr = np.array([1,2,3,4,5,6])
print(arr[-1])

6


In [28]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr[1,2])

6


### Slicing

In [30]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:4])

[2 3 4]


In [31]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:4:2])

[2 4]


In [35]:
arr = np.array([1,2,3,4,5,6])
print(arr[::2])

[1 3 5]


### Tipos de datos

In [2]:
import numpy as np
arr = np.array(["b","a"])
print(arr.dtype)

<U1


In [3]:
arr = np.array([1,2])
print(arr.dtype)

int32


In [4]:
arr = np.array([1.4,2.5])
print(arr.dtype)

float64


In [5]:
arr = np.array([1,2,3],dtype = "S")
# "i" = integer(entero)
# "b" = boolenao
# "f" = flotante
# "M" = datetime
# "O" = objeto
# "S"= string
print(arr)

[b'1' b'2' b'3']


In [7]:
arr = np.array([1.1,2.1,3.1])
print("pre", arr)
nuevo_arr= arr.astype("i")
print("post",nuevo_arr)

pre [1.1 2.1 3.1]
post [1 2 3]


### Copy vs View

In [8]:
arr = np.array([1,2,3])
x = arr.copy() 
y = arr.view() # Vista o reflejo 

print("arr",arr)
print("x",x)
print("y",y) 

arr[0]=0

print("arr",arr)
print("x",x)
print("y",y)

arr [1 2 3]
x [1 2 3]
y [1 2 3]
arr [0 2 3]
x [1 2 3]
y [0 2 3]


In [9]:
arr = np.array([1,2,4])
print("arr",arr)
x= arr.view()
print("x",x)

arr [1 2 4]
x [1 2 4]


### Concatenar

In [10]:
arr1 = np.array([1,2,3])
print("arr1",arr1)
arr2 = np.array([4,5,6])
print("arr2",arr2)
arr3=np.concatenate((arr1,arr2))
print("arr3",arr3)

arr1 [1 2 3]
arr2 [4 5 6]
arr3 [1 2 3 4 5 6]


### Busqueda

In [13]:
arr = np.array([1,2,2,4,5,5,4])
x = np.where(arr == 2) # Devuelve indice donde hay 2 y tipo de dato
print(x)

(array([1, 2], dtype=int64),)


### Ordenar

In [12]:
arr = np.array([2,5,6,4,1,3])
x = np.sort(arr)
print(x)

[1 2 3 4 5 6]


# Pandas

In [19]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [20]:
import pandas as pd

### Series

In [21]:
a = np.array([1,2,3])
srs = pd.Series(a)  # Da un indice a los datos
print(srs)
print(srs[0])

0    1
1    2
2    3
dtype: int32
1


In [22]:
srs = pd.Series(a,index = ["x","y","z"]) # Personalizar índice
print(srs)
print(srs["x"])

x    1
y    2
z    3
dtype: int32
1


In [23]:
pasos = {
    "lunes" : 440,
    "martes" : 620,
    "miercoles" : 700,
    "jueves" : 500,
    "viernes" : 150
    }
srs = pd.Series(pasos)
print(srs)

lunes        440
martes       620
miercoles    700
jueves       500
viernes      150
dtype: int64


In [24]:
srs = pd.Series(pasos,index=["lunes","miercoles","viernes"])
print(srs)

lunes        440
miercoles    700
viernes      150
dtype: int64


### Dataframe

In [32]:
mydataset= {
    "operador" : ["John Doe","Sr. X","Lorem ipsum"],
    "no. reloj" : [101,202,303]
}
df = pd.DataFrame(mydataset)
print(df)

      operador  no. reloj
0     John Doe        101
1        Sr. X        202
2  Lorem ipsum        303


In [33]:
df["no. reloj"]

0    101
1    202
2    303
Name: no. reloj, dtype: int64

In [34]:
df[df["no. reloj"] > 101]


operador  no. reloj
1        Sr. X        202
2  Lorem ipsum        303

In [35]:
df["asistencia"] = [True,False,True]

In [36]:
print(df)

      operador  no. reloj  asistencia
0     John Doe        101        True
1        Sr. X        202       False
2  Lorem ipsum        303        True


In [41]:
print(df.loc[2]) # Traer datos en indice 2

operador      Lorem ipsum
no. reloj             303
asistencia           True
Name: 2, dtype: object


In [42]:
print(df.loc[[0,1]]) # Traer un rango de datos

   operador  no. reloj  asistencia
0  John Doe        101        True
1     Sr. X        202       False


In [43]:
df = pd.DataFrame(mydataset, index = ["CEO","COO","CFO"])
print(df)

        operador  no. reloj
CEO     John Doe        101
COO        Sr. X        202
CFO  Lorem ipsum        303


In [44]:
print(df.loc["CEO"])

operador     John Doe
no. reloj         101
Name: CEO, dtype: object


In [45]:
print(df.loc[["CEO","COO"]])

     operador  no. reloj
CEO  John Doe        101
COO     Sr. X        202


### Vistas

In [57]:
df = pd.read_csv("../Python 3 Intermedio/dataset/Perfil de estudiante.csv")

In [63]:
df.head(3) # Sin nada adentro -> devuelve los 5 primeros registros 

Marca temporal   1.- ¿De dónde eres?  \
0  2023/06/27 7:42:12 p. m. GMT-6            Cd. Juárez   
1  2023/06/27 7:42:28 p. m. GMT-6  chihuahua, chihuahua   
2  2023/06/27 7:42:44 p. m. GMT-6   Chihuahua Chihuahua   

  2.- ¿Cuántos años tienes? 3.- ¿Estudias? 4.- ¿Trabajas?  \
0             Entre 21 y 24             Sí             No   
1             Entre 21 y 24             Sí             Sí   
2             Entre 18 y 20             Sí             Sí   

  5.- ¿Cuál es tu nivel de conocimiento en Python?  \
0                                           Básico   
1                                           Básico   
2                                           Básico   

  6.- ¿Qué tema relacionado con Python te gustaría aprender?  \
0                             Manejar bases de datos           
1                                    machine lerning           
2      Automatización y creación de apps/páginas web           

  7.- ¿Has participado en algún curso anteriormente en el IA Center?  \
0                                                 No                   
1                                                 Sí                   
2                                                 No                   

  8.- ¿Cuál es tu canción favorita?  
0                          The Wolf  
1                   eternity, anyma  
2    Cornerstone- Arctic Monkeys :)

In [62]:
df.tail(3) #Devuelve los ultimos 5 registros

Marca temporal                1.- ¿De dónde eres?  \
40  2023/06/28 10:12:04 p. m. GMT-6                          Chihuahua   
41   2023/06/29 2:00:51 a. m. GMT-6  Vivo en Ciudad Juárez. Soy cubana   
42   2023/07/03 1:55:24 p. m. GMT-6                      Ciudad Juarez   

   2.- ¿Cuántos años tienes? 3.- ¿Estudias? 4.- ¿Trabajas?  \
40             Entre 21 y 24             No             Sí   
41                 Más de 30             Sí             No   
42                 Más de 30             No             Sí   

   5.- ¿Cuál es tu nivel de conocimiento en Python?  \
40                                           Básico   
41                                       Intermedio   
42                                       Intermedio   

   6.- ¿Qué tema relacionado con Python te gustaría aprender?  \
40                   Machine Learning y Deep Learning           
41  Cómo escribir un código de forma profesional, ...           
42                                     Automatizacion           

   7.- ¿Has participado en algún curso anteriormente en el IA Center?  \
40                                                 Sí                   
41                                                 No                   
42                                                 No                   

                    8.- ¿Cuál es tu canción favorita?  
40                                            Runaway  
41  Hay varias, pero últimamente escucho mucho "Cu...  
42                              David Bowie - Heroes

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 9 columns):
 #   Column                                                              Non-Null Count  Dtype 
---  ------                                                              --------------  ----- 
 0   Marca temporal                                                      43 non-null     object
 1   1.- ¿De dónde eres?                                                 43 non-null     object
 2   2.- ¿Cuántos años tienes?                                           43 non-null     object
 3   3.- ¿Estudias?                                                      43 non-null     object
 4   4.- ¿Trabajas?                                                      43 non-null     object
 5   5.- ¿Cuál es tu nivel de conocimiento en Python?                    43 non-null     object
 6   6.- ¿Qué tema relacionado con Python te gustaría aprender?          43 non-null     object
 7   7.- ¿Has participado en algún

### CSV

In [65]:
df = pd.read_csv("../Python 3 Intermedio/dataset/Perfil de estudiante.csv")
print(df.to_string()) # Imprime en string

                     Marca temporal                        1.- ¿De dónde eres? 2.- ¿Cuántos años tienes? 3.- ¿Estudias? 4.- ¿Trabajas? 5.- ¿Cuál es tu nivel de conocimiento en Python?                                           6.- ¿Qué tema relacionado con Python te gustaría aprender? 7.- ¿Has participado en algún curso anteriormente en el IA Center?                             8.- ¿Cuál es tu canción favorita?
0    2023/06/27 7:42:12 p. m. GMT-6                                 Cd. Juárez             Entre 21 y 24             Sí             No                                           Básico                                                                               Manejar bases de datos                                                                 No                                                      The Wolf
1    2023/06/27 7:42:28 p. m. GMT-6                       chihuahua, chihuahua             Entre 21 y 24             Sí             Sí                                      

### JSON

In [66]:
df = pd.read_json("../Python 3 Intermedio/dataset/dataset.json")
print(df.to_string()) 

                                                 personas
0      {'nombre': 'Juan', 'edad': 25, 'ciudad': 'Madrid'}
1  {'nombre': 'María', 'edad': 30, 'ciudad': 'Barcelona'}
2   {'nombre': 'Pedro', 'edad': 35, 'ciudad': 'Valencia'}


### Limpieza de datos

In [105]:
data = {

    'Nombre': ['Juan', 'María', 'Pedro', 'Ana', 'Luis'],

    'Edad': [25, 32, None, 42, 28],

    'Fecha': ['31/01/2020', '31/01/2020', None, '31/01/2020', '01/31/2020'],

    'Género': ['M', 'F', None, 'F', 'M'],

    'Ciudad': ['Madrid', None, 'Madrid', 'Valencia', 'Barcelona'],

    'Altura': [175, 163, 180, 158, 170],

    'Peso': [70, None, 80, 60, 75],

    'Ingresos': [50000, 60000, 40000, None, 55000]

}

In [106]:
df = pd.DataFrame(data)
print(df)

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       NaN
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [72]:
df_sin_vacios = df.dropna() # Elimina campos nulos, None, Nall
print(df_sin_vacios.to_string())

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [107]:
df

Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       NaN
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0

In [74]:
df.dropna(inplace=True) #Quita registros con valores nulos
print(df.to_string())

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [108]:
df

Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       NaN
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0

In [109]:
print(df.to_string())

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       NaN
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [101]:
df_relleno = df.fillna("Sin registro")
print(df_relleno.to_string())

  Nombre          Edad         Fecha        Género        Ciudad  Altura          Peso      Ingresos
0   Juan          25.0    31/01/2020             M        Madrid     175          70.0       50000.0
1  María          32.0    31/01/2020             F  Sin registro     163  Sin registro       60000.0
2  Pedro  Sin registro  Sin registro  Sin registro        Madrid     180          80.0       40000.0
3    Ana          42.0    31/01/2020             F      Valencia     158          60.0  Sin registro
4   Luis          28.0    01/31/2020             M     Barcelona     170          75.0       55000.0


In [110]:
df_cero =df["Ingresos"].fillna(0)
print(df_cero)

0    50000.0
1    60000.0
2    40000.0
3        0.0
4    55000.0
Name: Ingresos, dtype: float64


In [116]:
df_limpio =df["Ingresos"].fillna(0)
print(df_limpio)

0    50000.0
1    60000.0
2    40000.0
3        0.0
4    55000.0
Name: Ingresos, dtype: float64


In [115]:
df

Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       NaN
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0

In [122]:
media = df["Ingresos"].mean()
print(media)

51250.0


In [123]:
df_media = df["Ingresos"].fillna(media)
print(df_media)

0    50000.0
1    60000.0
2    40000.0
3    51250.0
4    55000.0
Name: Ingresos, dtype: float64


In [126]:
mediana= df["Ingresos"].median()
print(mediana)

52500.0


In [127]:
df_mediana = df["Ingresos"].fillna(mediana)
print(df_mediana)

0    50000.0
1    60000.0
2    40000.0
3    52500.0
4    55000.0
Name: Ingresos, dtype: float64


In [142]:
moda = df["Ingresos"].mode()
print(moda)

0    40000.0
1    50000.0
2    55000.0
3    60000.0
Name: Ingresos, dtype: float64


In [128]:
df

Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       NaN
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0

In [129]:
df.loc[1,"Peso"] = 70
print(df)

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163  70.0   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       NaN
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [135]:
data = {

    'Nombre': ['Juan', 'María', 'Pedro', 'Ana', 'Luis','Luis'],

    'Edad': [25, 32, None, 42, 28,28],

    'Fecha': ['31/01/2020', '31/01/2020', None, '31/01/2020', '01/31/2020','01/31/2020'],

    'Género': ['M', 'F', None, 'F', 'M','M'],

    'Ciudad': ['Madrid', None, 'Madrid', 'Valencia', 'Barcelona','Barcelona'],

    'Altura': [175, 163, 180, 158, 170,170],

    'Peso': [70, None, 80, 60, 75,75],

    'Ingresos': [50000, 60000, 40000, None, 55000,55000]

}

In [137]:
df = pd.DataFrame(data)
df

Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       NaN
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0
5   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0

In [138]:
df.duplicated() # Hay duplicados?

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [141]:
df.drop_duplicates(inplace=True) #Eliminar duplicados
df

Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       NaN
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0

In [143]:
data = {
    "A" : [1,2,3,4,5],
    "B" : [5,4,3,2,1],
    "C" : [2,4,6,8,10]
}

In [144]:
df=pd.DataFrame(data)

In [145]:
df

A  B   C
0  1  5   2
1  2  4   4
2  3  3   6
3  4  2   8
4  5  1  10

In [147]:
df.corr() # Coeficiente de correlación

A    B    C
A  1.0 -1.0  1.0
B -1.0  1.0 -1.0
C  1.0 -1.0  1.0

# Matplotlib

In [148]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [149]:
import matplotlib as plt

In [150]:
import matplotlib.pyplot as plt

### Plot

In [ ]:
import numpy as np
puntos_x = np.array([0,4,8,16])
puntos_y = np.array([6,12,24,])