# Numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

### Arreglos

In [3]:
arr = np.array([1,2,3])

print(arr)

[1 2 3]


In [4]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
arr = np.array([1,2,3,4,5,6], ndmin=3)
print(arr.ndim) #Propiedad dimensión
print(arr)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])

3
[[[1 2 3 4 5 6]]]
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
1


In [12]:
arr = np.zeros((2,2))
print(arr)

[[0. 0.]
 [0. 0.]]


In [9]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
arr = np.random.rand(3,3)
print(arr)

[[0.54926355 0.30849339 0.42340303]
 [0.22142018 0.1214385  0.28110756]
 [0.74504948 0.15098718 0.25804592]]


### Operaciones

In [13]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = np.add(arr1,arr2)
print(arr3)

[5 7 9]


In [16]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3=np.subtract(arr2,arr1)
print(arr3)

[3 3 3]


In [17]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3=np.multiply(arr2,arr1)
print(arr3)

[ 4 10 18]


In [18]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3=np.divide(arr1,arr2)
print(arr3)

[0.25 0.4  0.5 ]


### Agregación (Media, mediana, moda, etc...)

In [20]:
arr = [1,5,7]
media = np.mean(arr)
print(media)

4.333333333333333


In [21]:
arr = [1,5,7]
mediana = np.median(arr)
print(mediana)

5.0


In [22]:
arr = [1,5,7]
maximo = np.max(arr)
print(maximo)

7


In [23]:
arr = [1,5,7]
minimo = np.min(arr)
print(minimo)

1


### Indexación

In [24]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])

1


In [25]:
arr = np.array([1,2,3,4,5,6])
print(arr[-1])

6


In [28]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr[1,2])

6


### Slicing

In [30]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:4])

[2 3 4]


In [31]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:4:2])

[2 4]


In [35]:
arr = np.array([1,2,3,4,5,6])
print(arr[::2])

[1 3 5]


### Tipos de datos

### Copy vs View

### Concatenar

### Busqueda

In [ ]:
arr = np.array([1,2,2,4,5,5,6])
x = np.where(arr == 5)
print(x)

### Ordenar

In [ ]:
arr = np.

# Pandas

### Series